#=================================================================
# minio
#=================================================================
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: chengliuxiang
  secretKey: chengliuxiang