---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Summer Snow.
--- DateTime: 2024/11/12 11:52
---

local key=KEYS[1] -- 操作的 Key
local noteId=ARGV[1] -- 笔记ID
local expireSeconds=ARGV[2] -- 过期时间（秒）

redis.call("BF.ADD",key,noteId);

-- 设置过期时间
redis.call("EXPIRE",key,expireSeconds)
return 0