---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Summer Snow.
--- DateTime: 2024/9/19 17:03
---

local key=KEYS[1]
local followUserId=ARGV[1]
local timestamp=ARGV[2]
local expireSeconds=ARGV[3]

-- ZADD 添加关注关系
redis.call('ZADD',key,timestamp,followUserId)

-- 设置过期时间
redis.call('EXPIRE',key,expireSeconds)
return 0